
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="apple-touch-icon" href="icon.png">
    <!-- Place favicon.ico in the root directory -->
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/main.css">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400&display=swap" rel="stylesheet">


    <meta name="theme-color" content="#E7E7EA">
</head>

<body data-gr-c-s-loaded="true">
<!--[if IE]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade
    your browser</a> to improve your experience and security.</p>
<![endif]-->

<!-- Add your site or application content here -->
<div class="block header">
    <div class="header__image">

    </div>
    <div class="header__title">
        <h1>Tickets Portal v${version}</h1>
    </div>
    <div class="header__options">

    </div>

</div>
<div class="bottom-blocks">
    <div class="main-title">


    </div>
    <div class="queue">
        <div class="queue-header">
            <h2>🎫 Here are your tickets! </h2>
        </div>
        <div class="queue-list">
            <div class="ticket">
                <div class="ticket-header">
                    <h4>Your tickets for: </h4>
                    <h3>Really Cool Concert </h3>
                </div>
                <div class="codesIds">Tickets Unique Code:  <span>${ticketsCode}</span></div>
                <div class="codesIds">Session ID <span>${sessionId}</span></div>
                <div class="codesIds">Reservation ID  <span>${reservationId}</span></div>
                <div class="ticket-info">
                    <h4>Aug 24, 2020 </h4>
                    <h4>VIP Tickets</h4>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="button-layer">
    <a  href="#" class="main-button" >
        Download Your Tickets
    </a>
</div>



<script src="js/vendor/modernizr-3.7.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.4.1.min.js"><\/script>')</script>
<script src="js/plugins.js"></script>

<script type="text/javascript">


</script>




</body>

</html>
